// SPDX-License-Identifier: MIT
// repository.go: PushRepository is the storage seam for the push pipeline.
//
// The push pipeline needs three things to land a single Apply:
//
//   - a PushRun row (the audit trail entry);
//   - a ConfigSnapshot row (the parsed *ConfigData captured at push time);
//   - a backup file on disk (the raw device-native bytes the operator
//     could restore from).
//
// These live in three different stores today (in-memory for tests;
// CloverDB collection + filesystem backup root for prod). PushRepository
// is the single interface that hides that split so internal/push/Service
// stays storage-agnostic.
package push

import (
	"io"
)

// PushRepository persists the three push artifacts (run, snapshot, backup).
// Every method MUST be safe to call concurrently. The in-memory impl is
// used by tests; the production impl wraps the existing CloverDB collection
// wrappers plus the filesystem backup store.
type PushRepository interface {
	// --- push runs (audit trail) ---

	// AppendRun writes a PushRun row. The run's ID is generated by the
	// caller; the repository preserves it verbatim.
	AppendRun(r PushRun) error

	// ListRuns returns the most recent `limit` runs for a device, newest
	// first. limit<=0 returns every run.
	ListRuns(deviceID string, limit int) ([]PushRun, error)

	// LatestRun returns the most recent run for a device, or
	// (PushRun{}, ErrNotFound) when the device has no runs.
	LatestRun(deviceID string) (PushRun, error)

	// --- snapshots (parsed *ConfigData) ---

	// SaveSnapshot persists a ConfigSnapshot. The repo assigns the ID if
	// the caller left it empty; otherwise the ID is preserved. Returns
	// the ID as stored.
	SaveSnapshot(s ConfigSnapshot) (id string, err error)

	// GetSnapshot loads a snapshot by ID. Returns ErrNotFound when no
	// row matches.
	GetSnapshot(id string) (ConfigSnapshot, error)

	// ListSnapshots returns the most recent `limit` snapshots for a device,
	// newest first. limit<=0 returns every snapshot.
	ListSnapshots(deviceID string, limit int) ([]ConfigSnapshot, error)

	// LatestSnapshot returns the most recent snapshot for a device, or
	// (ConfigSnapshot{}, ErrNotFound) when none exist.
	LatestSnapshot(deviceID string) (ConfigSnapshot, error)

	// --- backup files (raw device-native bytes) ---

	// SaveBackup persists raw device-native bytes. ext is the OS-specific
	// file extension ("xml" for OPNsense, "conf" for OpenWrt UCI, etc.).
	// Returns the relative path from the configured backup root; the
	// caller combines it with the root for absolute access.
	SaveBackup(deviceID, runID, ext string, raw []byte) (relpath string, err error)

	// OpenBackup returns a reader for a previously-saved backup. The
	// caller MUST close the reader when done.
	OpenBackup(deviceID, runID string) (io.ReadCloser, error)

	// KeepN trims backups to the most recent N per device. n<=0 is a no-op.
	KeepN(deviceID string, n int) error
}

// ErrNotFound is returned when a lookup by ID or device misses. Concrete
// store impls wrap their underlying not-found errors with this so the
// service layer can branch on a single type.
type NotFoundError struct {
	What string // "run", "snapshot", "backup"
	ID   string // the missing key
}

func (e *NotFoundError) Error() string {
	return "push: " + e.What + " not found: " + e.ID
}