// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_sqlite

import (
	"database/sql"
)

type Brand struct {
	ID    int64
	Brand string
}

type Connection struct {
	ID                        int64
	FromDevicePortModelPortID int64
	FromDevicePortDeviceID    int64
	FromIpSegment             sql.NullString
	ToDevicePortModelPortID   int64
	ToDevicePortDeviceID      int64
	ToIpSegment               sql.NullString
	ConnectionType            sql.NullInt64
}

type Connectiontype struct {
	ID             int64
	ConnectionType string
}

type Device struct {
	ID          int64
	Label       string
	ModelID     int64
	ZoneID      sql.NullInt64
	Proprietary sql.NullInt64
}

type DevicePortValidation struct {
	Modelportid            int64
	Deviceid               int64
	Devicemodelid          int64
	Modelportdevicemodelid int64
	Isvalidconfiguration   int64
}

type Deviceclass struct {
	ID   int64
	Name string
}

type Deviceport struct {
	ModelPortID int64
	DeviceID    int64
}

type Modeldevice struct {
	ID      int64
	Model   string
	Brand   int64
	ClassID int64
}

type Modelport struct {
	ID        int64
	Name      string
	Positionx int64
	Positiony int64
	ModelID   int64
}

type Policy struct {
	ID                   int64
	Name                 string
	Description          string
	AssociatedConnection sql.NullInt64
	Todo                 sql.NullString
}

type Proprietary struct {
	ID          int64
	Proprietary string
}

type Zone struct {
	ID           int64
	Name         string
	Father       sql.NullInt64
	Granularity  sql.NullInt64
	Proprietary  sql.NullInt64
	LocationType sql.NullInt64
}

type Zonetype struct {
	ID           int64
	LocationType string
}
