// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlcbasicops

import (
	"context"
	"database/sql"
)

const addBrand = `-- name: AddBrand :exec
INSERT INTO brand (
	brand
) VALUES (
	?
)
`

func (q *Queries) AddBrand(ctx context.Context, brand string) error {
	_, err := q.db.ExecContext(ctx, addBrand, brand)
	return err
}

const addConnection = `-- name: AddConnection :exec
;

INSERT INTO Connection (
	from_device_port_device_id,
	from_device_port_model_port_id,
	to_device_port_device_id,
	to_device_port_model_port_id,
	connection_type
) VALUES (
	?,?,?,?,?
)
`

type AddConnectionParams struct {
	FromDevicePortDeviceID    int64
	FromDevicePortModelPortID int64
	ToDevicePortDeviceID      int64
	ToDevicePortModelPortID   int64
	ConnectionType            sql.NullInt64
}

func (q *Queries) AddConnection(ctx context.Context, arg AddConnectionParams) error {
	_, err := q.db.ExecContext(ctx, addConnection,
		arg.FromDevicePortDeviceID,
		arg.FromDevicePortModelPortID,
		arg.ToDevicePortDeviceID,
		arg.ToDevicePortModelPortID,
		arg.ConnectionType,
	)
	return err
}

const addDevice = `-- name: AddDevice :exec
INSERT INTO Device(
    label,
    model_id, 
    zone_id,
    proprietary
) VALUES (
    ?,?,?,?
)
`

type AddDeviceParams struct {
	Label       string
	ModelID     int64
	ZoneID      sql.NullInt64
	Proprietary sql.NullInt64
}

func (q *Queries) AddDevice(ctx context.Context, arg AddDeviceParams) error {
	_, err := q.db.ExecContext(ctx, addDevice,
		arg.Label,
		arg.ModelID,
		arg.ZoneID,
		arg.Proprietary,
	)
	return err
}

const addDeviceClass = `-- name: AddDeviceClass :exec
INSERT INTO DeviceClass(
	name
) VALUES (
  ?	
)
`

func (q *Queries) AddDeviceClass(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addDeviceClass, name)
	return err
}

const addDevicePort = `-- name: AddDevicePort :exec
;

INSERT INTO DevicePort (
	device_id,model_port_id
) VALUES (
	?,?
)
`

type AddDevicePortParams struct {
	DeviceID    int64
	ModelPortID int64
}

func (q *Queries) AddDevicePort(ctx context.Context, arg AddDevicePortParams) error {
	_, err := q.db.ExecContext(ctx, addDevicePort, arg.DeviceID, arg.ModelPortID)
	return err
}

const addModel = `-- name: AddModel :exec
INSERT INTO ModelDevice(
    model,
    brand,
    class_id
) VALUES (
    ?,?,?
)
`

type AddModelParams struct {
	Model   string
	Brand   int64
	ClassID int64
}

func (q *Queries) AddModel(ctx context.Context, arg AddModelParams) error {
	_, err := q.db.ExecContext(ctx, addModel, arg.Model, arg.Brand, arg.ClassID)
	return err
}

const addModelPort = `-- name: AddModelPort :exec
INSERT INTO ModelPort(
    name,
    positionx,
    positiony,
    model_id
) VALUES (
    ?,?,?,?
)
`

type AddModelPortParams struct {
	Name      string
	Positionx int64
	Positiony int64
	ModelID   int64
}

func (q *Queries) AddModelPort(ctx context.Context, arg AddModelPortParams) error {
	_, err := q.db.ExecContext(ctx, addModelPort,
		arg.Name,
		arg.Positionx,
		arg.Positiony,
		arg.ModelID,
	)
	return err
}

const addProprietary = `-- name: AddProprietary :exec
INSERT INTO Proprietary(
	proprietary 
) VALUES (
  ?	
)
`

func (q *Queries) AddProprietary(ctx context.Context, proprietary string) error {
	_, err := q.db.ExecContext(ctx, addProprietary, proprietary)
	return err
}

const addZone = `-- name: AddZone :exec
INSERT INTO Zone(
name,father,location_type,proprietary
) VALUES (
?,?,?,?	
)
`

type AddZoneParams struct {
	Name         string
	Father       sql.NullInt64
	LocationType sql.NullInt64
	Proprietary  sql.NullInt64
}

func (q *Queries) AddZone(ctx context.Context, arg AddZoneParams) error {
	_, err := q.db.ExecContext(ctx, addZone,
		arg.Name,
		arg.Father,
		arg.LocationType,
		arg.Proprietary,
	)
	return err
}

const addZoneType = `-- name: AddZoneType :exec
INSERT INTO Zonetype(
	location_type
) VALUES (
  ?	
)
`

func (q *Queries) AddZoneType(ctx context.Context, locationType string) error {
	_, err := q.db.ExecContext(ctx, addZoneType, locationType)
	return err
}

const basicGetBrands = `-- name: BasicGetBrands :many
SELECT id, brand
FROM Brand
`

func (q *Queries) BasicGetBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, basicGetBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.ID, &i.Brand); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetConnectionTypes = `-- name: BasicGetConnectionTypes :many
SELECT id, connection_type
FROM ConnectionType
`

func (q *Queries) BasicGetConnectionTypes(ctx context.Context) ([]Connectiontype, error) {
	rows, err := q.db.QueryContext(ctx, basicGetConnectionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connectiontype
	for rows.Next() {
		var i Connectiontype
		if err := rows.Scan(&i.ID, &i.ConnectionType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetConnections = `-- name: BasicGetConnections :many
SELECT id, from_device_port_model_port_id, from_device_port_device_id, from_ip_segment, to_device_port_model_port_id, to_device_port_device_id, to_ip_segment, connection_type
FROM Connection
`

func (q *Queries) BasicGetConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, basicGetConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.FromDevicePortModelPortID,
			&i.FromDevicePortDeviceID,
			&i.FromIpSegment,
			&i.ToDevicePortModelPortID,
			&i.ToDevicePortDeviceID,
			&i.ToIpSegment,
			&i.ConnectionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetDeviceClasses = `-- name: BasicGetDeviceClasses :many


SELECT id, name
FROM DeviceClass
`

// - Basic getter
func (q *Queries) BasicGetDeviceClasses(ctx context.Context) ([]Deviceclass, error) {
	rows, err := q.db.QueryContext(ctx, basicGetDeviceClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deviceclass
	for rows.Next() {
		var i Deviceclass
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetDevicePorts = `-- name: BasicGetDevicePorts :many
SELECT model_port_id, device_id
FROM DevicePort
`

func (q *Queries) BasicGetDevicePorts(ctx context.Context) ([]Deviceport, error) {
	rows, err := q.db.QueryContext(ctx, basicGetDevicePorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deviceport
	for rows.Next() {
		var i Deviceport
		if err := rows.Scan(&i.ModelPortID, &i.DeviceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetDevices = `-- name: BasicGetDevices :many
SELECT id, label, model_id, zone_id, proprietary
FROM Device
`

func (q *Queries) BasicGetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, basicGetDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.ModelID,
			&i.ZoneID,
			&i.Proprietary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetModelDevices = `-- name: BasicGetModelDevices :many
SELECT id, model, brand, class_id
FROM ModelDevice
`

func (q *Queries) BasicGetModelDevices(ctx context.Context) ([]Modeldevice, error) {
	rows, err := q.db.QueryContext(ctx, basicGetModelDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modeldevice
	for rows.Next() {
		var i Modeldevice
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Brand,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetModelPorts = `-- name: BasicGetModelPorts :many
SELECT id, name, positionx, positiony, model_id
FROM ModelPort
`

func (q *Queries) BasicGetModelPorts(ctx context.Context) ([]Modelport, error) {
	rows, err := q.db.QueryContext(ctx, basicGetModelPorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modelport
	for rows.Next() {
		var i Modelport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Positionx,
			&i.Positiony,
			&i.ModelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetPolicies = `-- name: BasicGetPolicies :many
SELECT id, name, description, associated_connection, TODO
FROM Policy
`

func (q *Queries) BasicGetPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, basicGetPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AssociatedConnection,
			&i.Todo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetProprietaries = `-- name: BasicGetProprietaries :many
SELECT id, proprietary
FROM Proprietary
`

func (q *Queries) BasicGetProprietaries(ctx context.Context) ([]Proprietary, error) {
	rows, err := q.db.QueryContext(ctx, basicGetProprietaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proprietary
	for rows.Next() {
		var i Proprietary
		if err := rows.Scan(&i.ID, &i.Proprietary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetZoneTypes = `-- name: BasicGetZoneTypes :many
SELECT id, location_type
FROM ZoneType
`

func (q *Queries) BasicGetZoneTypes(ctx context.Context) ([]Zonetype, error) {
	rows, err := q.db.QueryContext(ctx, basicGetZoneTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zonetype
	for rows.Next() {
		var i Zonetype
		if err := rows.Scan(&i.ID, &i.LocationType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const basicGetZones = `-- name: BasicGetZones :many
SELECT id, name, father, granularity, proprietary, location_type
FROM Zone
`

func (q *Queries) BasicGetZones(ctx context.Context) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, basicGetZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Father,
			&i.Granularity,
			&i.Proprietary,
			&i.LocationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDevices = `-- name: CountDevices :one
SELECT count(*)
FROM Device
WHERE label = ?
`

func (q *Queries) CountDevices(ctx context.Context, label string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices, label)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelPorts = `-- name: CountModelPorts :one
SELECT count(*)
FROM ModelPort mp
LEFT JOIN ModelDevice m on mp.model_id=m.id
WHERE mp.name=? and m.model=? LIMIT 1
`

type CountModelPortsParams struct {
	Name  string
	Model string
}

func (q *Queries) CountModelPorts(ctx context.Context, arg CountModelPortsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelPorts, arg.Name, arg.Model)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModels = `-- name: CountModels :one
SELECT count(*)
FROM ModelDevice
WHERE model = ?
`

func (q *Queries) CountModels(ctx context.Context, model string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModels, model)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countZones = `-- name: CountZones :one
SELECT count(*)
FROM Zone
WHERE name=?
`

func (q *Queries) CountZones(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countZones, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM Brand WHERE brand = ?
`

func (q *Queries) DeleteBrand(ctx context.Context, brand string) error {
	_, err := q.db.ExecContext(ctx, deleteBrand, brand)
	return err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM Connection 
WHERE
    id = ?
`

func (q *Queries) DeleteConnection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, id)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM Device WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deleteDeviceClass = `-- name: DeleteDeviceClass :exec
DELETE FROM DeviceClass WHERE name = ?
`

func (q *Queries) DeleteDeviceClass(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceClass, name)
	return err
}

const deleteDevicePort = `-- name: DeleteDevicePort :exec
DELETE FROM DevicePort WHERE device_id = ? AND model_port_id = ?
`

type DeleteDevicePortParams struct {
	DeviceID    int64
	ModelPortID int64
}

func (q *Queries) DeleteDevicePort(ctx context.Context, arg DeleteDevicePortParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevicePort, arg.DeviceID, arg.ModelPortID)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM ModelDevice WHERE id = ?
`

func (q *Queries) DeleteModel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const deleteModelPort = `-- name: DeleteModelPort :exec
DELETE FROM ModelPort WHERE id = ?
`

func (q *Queries) DeleteModelPort(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteModelPort, id)
	return err
}

const deleteProprietary = `-- name: DeleteProprietary :exec
DELETE FROM Proprietary WHERE proprietary = ?
`

func (q *Queries) DeleteProprietary(ctx context.Context, proprietary string) error {
	_, err := q.db.ExecContext(ctx, deleteProprietary, proprietary)
	return err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM Zone WHERE id = ?
`

func (q *Queries) DeleteZone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const deleteZoneType = `-- name: DeleteZoneType :exec
DELETE FROM Zonetype WHERE location_type = ?
`

func (q *Queries) DeleteZoneType(ctx context.Context, locationType string) error {
	_, err := q.db.ExecContext(ctx, deleteZoneType, locationType)
	return err
}

const getBrandId = `-- name: GetBrandId :one
SELECT id FROM Brand WHERE brand = ? LIMIT 1
`

func (q *Queries) GetBrandId(ctx context.Context, brand string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBrandId, brand)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBrands = `-- name: GetBrands :many


SELECT brand
FROM brand
`

// -- Getters and setters for each table
// - Brand
func (q *Queries) GetBrands(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var brand string
		if err := rows.Scan(&brand); err != nil {
			return nil, err
		}
		items = append(items, brand)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassId = `-- name: GetClassId :one
SELECT id FROM DeviceClass WHERE name = ? LIMIT 1
`

func (q *Queries) GetClassId(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClassId, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConnectionId = `-- name: GetConnectionId :many
SELECT 
    id,
    from_device_port_device_id,
    from_device_port_model_port_id,
    to_device_port_device_id,
    to_device_port_model_port_id,
    connection_type
FROM Connection
WHERE 
    from_device_port_device_id = ? AND
    from_device_port_model_port_id = ? AND
    to_device_port_device_id = ? AND
    to_device_port_model_port_id = ?
`

type GetConnectionIdParams struct {
	FromDevicePortDeviceID    int64
	FromDevicePortModelPortID int64
	ToDevicePortDeviceID      int64
	ToDevicePortModelPortID   int64
}

type GetConnectionIdRow struct {
	ID                        int64
	FromDevicePortDeviceID    int64
	FromDevicePortModelPortID int64
	ToDevicePortDeviceID      int64
	ToDevicePortModelPortID   int64
	ConnectionType            sql.NullInt64
}

func (q *Queries) GetConnectionId(ctx context.Context, arg GetConnectionIdParams) ([]GetConnectionIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getConnectionId,
		arg.FromDevicePortDeviceID,
		arg.FromDevicePortModelPortID,
		arg.ToDevicePortDeviceID,
		arg.ToDevicePortModelPortID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectionIdRow
	for rows.Next() {
		var i GetConnectionIdRow
		if err := rows.Scan(
			&i.ID,
			&i.FromDevicePortDeviceID,
			&i.FromDevicePortModelPortID,
			&i.ToDevicePortDeviceID,
			&i.ToDevicePortModelPortID,
			&i.ConnectionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnections = `-- name: GetConnections :many

SELECT
    c.id,
    d.label as fromdevname,
    mp.name as frommodelportname,
    d2.label as todevname,
    mp2.name as tomodelportname,
    ct.connection_type,
    z.id as fromzoneid,
    z.name as fromzonename,
    z2.id as tozoneid,
    z2.name as tozonename
FROM Connection c
LEFT JOIN DevicePort dp on c.from_device_port_device_id=dp.device_id and c.from_device_port_model_port_id=dp.model_port_id
LEFT JOIN DevicePort dp2 on c.to_device_port_device_id=dp2.device_id and c.to_device_port_model_port_id=dp2.model_port_id
LEFT JOIN ModelPort mp on dp.model_port_id=mp.id 
LEFT JOIN Device d on dp.device_id=d.id 
LEFT JOIN ModelPort mp2 on dp2.model_port_id=mp2.id 
LEFT JOIN Device d2 on dp2.device_id=d2.id 
LEFT JOIN ConnectionType ct on c.connection_type=ct.id
LEFT JOIN Zone z on d.zone_id=z.id
LEFT JOIN Zone z2 on d2.zone_id=z2.id
`

type GetConnectionsRow struct {
	ID                int64
	Fromdevname       sql.NullString
	Frommodelportname sql.NullString
	Todevname         sql.NullString
	Tomodelportname   sql.NullString
	ConnectionType    sql.NullString
	Fromzoneid        sql.NullInt64
	Fromzonename      sql.NullString
	Tozoneid          sql.NullInt64
	Tozonename        sql.NullString
}

// - Connection
func (q *Queries) GetConnections(ctx context.Context) ([]GetConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectionsRow
	for rows.Next() {
		var i GetConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Fromdevname,
			&i.Frommodelportname,
			&i.Todevname,
			&i.Tomodelportname,
			&i.ConnectionType,
			&i.Fromzoneid,
			&i.Fromzonename,
			&i.Tozoneid,
			&i.Tozonename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceClasses = `-- name: GetDeviceClasses :many

SELECT name
FROM DeviceClass
`

// - DeviceClass
func (q *Queries) GetDeviceClasses(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceId = `-- name: GetDeviceId :one
SELECT id
FROM Device
WHERE label = ? LIMIT 1
`

func (q *Queries) GetDeviceId(ctx context.Context, label string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeviceId, label)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDevicePorts = `-- name: GetDevicePorts :many

SELECT dp.device_id,dp.model_port_id,mp.name,d.label,mp.positionx,mp.positiony
FROM DevicePort dp
LEFT JOIN ModelPort mp on dp.model_port_id=mp.id 
LEFT JOIN Device d on dp.device_id=d.id
`

type GetDevicePortsRow struct {
	DeviceID    int64
	ModelPortID int64
	Name        sql.NullString
	Label       sql.NullString
	Positionx   sql.NullInt64
	Positiony   sql.NullInt64
}

// - DevicePort
func (q *Queries) GetDevicePorts(ctx context.Context) ([]GetDevicePortsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDevicePorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicePortsRow
	for rows.Next() {
		var i GetDevicePortsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.ModelPortID,
			&i.Name,
			&i.Label,
			&i.Positionx,
			&i.Positiony,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevices = `-- name: GetDevices :many

SELECT 
    d.id,
    d.label,
    md.model,
    b.brand,
    z.name as zonename,
    z.id as zoneid,
    z2.name as zonefathername,
    p.proprietary
FROM Device d 
LEFT JOIN ModelDevice md on d.model_id=md.id
LEFT JOIN Proprietary p on d.proprietary=p.id
LEFT JOIN Zone z on d.zone_id=z.id
LEFT JOIN Brand b on md.brand=b.id
LEFT JOIN Zone z2 on z.father=z2.id
`

type GetDevicesRow struct {
	ID             int64
	Label          string
	Model          sql.NullString
	Brand          sql.NullString
	Zonename       sql.NullString
	Zoneid         sql.NullInt64
	Zonefathername sql.NullString
	Proprietary    sql.NullString
}

// - Device
func (q *Queries) GetDevices(ctx context.Context) ([]GetDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesRow
	for rows.Next() {
		var i GetDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Model,
			&i.Brand,
			&i.Zonename,
			&i.Zoneid,
			&i.Zonefathername,
			&i.Proprietary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelId = `-- name: GetModelId :one
SELECT id
FROM ModelDevice
WHERE model = ? LIMIT 1
`

func (q *Queries) GetModelId(ctx context.Context, model string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getModelId, model)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getModelPortId = `-- name: GetModelPortId :one
SELECT mp.id
FROM ModelPort mp
LEFT JOIN ModelDevice m on mp.model_id=m.id
WHERE mp.name=? and m.model=? LIMIT 1
`

type GetModelPortIdParams struct {
	Name  string
	Model string
}

func (q *Queries) GetModelPortId(ctx context.Context, arg GetModelPortIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getModelPortId, arg.Name, arg.Model)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getModelPorts = `-- name: GetModelPorts :many

SELECT 
    mp.id,
    mp.name,
    mp.positionx,
    mp.positiony,
    m.model,
    b.brand
FROM ModelPort mp
LEFT JOIN ModelDevice m on mp.model_id=m.id
LEFT JOIN brand b on m.brand=b.id
`

type GetModelPortsRow struct {
	ID        int64
	Name      string
	Positionx int64
	Positiony int64
	Model     sql.NullString
	Brand     sql.NullString
}

// - ModelPort
func (q *Queries) GetModelPorts(ctx context.Context) ([]GetModelPortsRow, error) {
	rows, err := q.db.QueryContext(ctx, getModelPorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModelPortsRow
	for rows.Next() {
		var i GetModelPortsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Positionx,
			&i.Positiony,
			&i.Model,
			&i.Brand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModels = `-- name: GetModels :many

SELECT 
    m.id,
    m.model,
    b.brand,
    c.name AS class_name
FROM ModelDevice m
JOIN Brand b ON m.brand = b.id
JOIN DeviceClass c ON m.class_id = c.id
`

type GetModelsRow struct {
	ID        int64
	Model     string
	Brand     string
	ClassName string
}

// - Model
func (q *Queries) GetModels(ctx context.Context) ([]GetModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModelsRow
	for rows.Next() {
		var i GetModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Brand,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPossiblePortsAll = `-- name: GetPossiblePortsAll :many


SELECT Device.id as deviceid, ModelPort.id as modelid
FROM Device
CROSS JOIN ModelPort
`

type GetPossiblePortsAllRow struct {
	Deviceid int64
	Modelid  int64
}

// -- Special
func (q *Queries) GetPossiblePortsAll(ctx context.Context) ([]GetPossiblePortsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, getPossiblePortsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPossiblePortsAllRow
	for rows.Next() {
		var i GetPossiblePortsAllRow
		if err := rows.Scan(&i.Deviceid, &i.Modelid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPossiblePortsDevice = `-- name: GetPossiblePortsDevice :many
SELECT Device.id as deviceid, ModelPort.id as modelid
FROM Device
CROSS JOIN ModelPort
WHERE Device.id = ?
`

type GetPossiblePortsDeviceRow struct {
	Deviceid int64
	Modelid  int64
}

func (q *Queries) GetPossiblePortsDevice(ctx context.Context, id int64) ([]GetPossiblePortsDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getPossiblePortsDevice, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPossiblePortsDeviceRow
	for rows.Next() {
		var i GetPossiblePortsDeviceRow
		if err := rows.Scan(&i.Deviceid, &i.Modelid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProprietaries = `-- name: GetProprietaries :many

SELECT proprietary 
FROM Proprietary
`

// - Proprietary
func (q *Queries) GetProprietaries(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProprietaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var proprietary string
		if err := rows.Scan(&proprietary); err != nil {
			return nil, err
		}
		items = append(items, proprietary)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProprietary = `-- name: GetProprietary :one
SELECT id 
FROM Proprietary
WHERE proprietary=? LIMIT 1
`

func (q *Queries) GetProprietary(ctx context.Context, proprietary string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProprietary, proprietary)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneId = `-- name: GetZoneId :one
SELECT id
FROM Zone
WHERE name=? LIMIT 1
`

func (q *Queries) GetZoneId(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getZoneId, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneType = `-- name: GetZoneType :one
SELECT id
FROM Zonetype
WHERE location_type=? LIMIT 1
`

func (q *Queries) GetZoneType(ctx context.Context, locationType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getZoneType, locationType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneTypes = `-- name: GetZoneTypes :many

SELECT location_type
FROM Zonetype
`

// - ZoneTypes
func (q *Queries) GetZoneTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getZoneTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location_type string
		if err := rows.Scan(&location_type); err != nil {
			return nil, err
		}
		items = append(items, location_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZones = `-- name: GetZones :many

SELECT z1.id as id,z1.name as name,z2.id as fatherid,z2.name as father,Zonetype.location_type,proprietary.proprietary
FROM Zone z1 JOIN proprietary JOIN ZoneType LEFT JOIN Zone z2 on z1.father=z2.id GROUP BY z1.id
`

type GetZonesRow struct {
	ID           int64
	Name         string
	Fatherid     sql.NullInt64
	Father       sql.NullString
	LocationType string
	Proprietary  string
}

// - Zone
func (q *Queries) GetZones(ctx context.Context) ([]GetZonesRow, error) {
	rows, err := q.db.QueryContext(ctx, getZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetZonesRow
	for rows.Next() {
		var i GetZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Fatherid,
			&i.Father,
			&i.LocationType,
			&i.Proprietary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :exec
;

UPDATE connection
SET
    from_device_port_device_id = ?,
    from_device_port_model_port_id = ?,
    to_device_port_device_id = ?,
    to_device_port_model_port_id = ?
WHERE
    id = ?
`

type UpdateConnectionParams struct {
	FromDevicePortDeviceID    int64
	FromDevicePortModelPortID int64
	ToDevicePortDeviceID      int64
	ToDevicePortModelPortID   int64
	ID                        int64
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateConnection,
		arg.FromDevicePortDeviceID,
		arg.FromDevicePortModelPortID,
		arg.ToDevicePortDeviceID,
		arg.ToDevicePortModelPortID,
		arg.ID,
	)
	return err
}
