// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc_sqlite

import (
	"context"
	"database/sql"
)

const addBrand = `-- name: AddBrand :exec
INSERT INTO brand (
	brand
) VALUES (
	?
)
`

func (q *Queries) AddBrand(ctx context.Context, brand string) error {
	_, err := q.db.ExecContext(ctx, addBrand, brand)
	return err
}

const addDeviceClass = `-- name: AddDeviceClass :exec
INSERT INTO DeviceClass(
	name
) VALUES (
  ?	
)
`

func (q *Queries) AddDeviceClass(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addDeviceClass, name)
	return err
}

const addProprietary = `-- name: AddProprietary :exec
INSERT INTO Proprietary(
	proprietary 
) VALUES (
  ?	
)
`

func (q *Queries) AddProprietary(ctx context.Context, proprietary string) error {
	_, err := q.db.ExecContext(ctx, addProprietary, proprietary)
	return err
}

const addZone = `-- name: AddZone :exec
INSERT INTO Zone(
name,father,location_type,proprietary
) VALUES (
?,?,?,?	
)
`

type AddZoneParams struct {
	Name         string
	Father       sql.NullInt64
	LocationType sql.NullInt64
	Proprietary  sql.NullInt64
}

func (q *Queries) AddZone(ctx context.Context, arg AddZoneParams) error {
	_, err := q.db.ExecContext(ctx, addZone,
		arg.Name,
		arg.Father,
		arg.LocationType,
		arg.Proprietary,
	)
	return err
}

const addZoneType = `-- name: AddZoneType :exec
INSERT INTO Zonetype(
	location_type
) VALUES (
  ?	
)
`

func (q *Queries) AddZoneType(ctx context.Context, locationType string) error {
	_, err := q.db.ExecContext(ctx, addZoneType, locationType)
	return err
}

const getBrands = `-- name: GetBrands :many
SELECT brand
FROM brand
`

func (q *Queries) GetBrands(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var brand string
		if err := rows.Scan(&brand); err != nil {
			return nil, err
		}
		items = append(items, brand)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceClasses = `-- name: GetDeviceClasses :many
SELECT name
FROM DeviceClass
`

func (q *Queries) GetDeviceClasses(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProprietaries = `-- name: GetProprietaries :many
SELECT proprietary 
FROM Proprietary
`

func (q *Queries) GetProprietaries(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProprietaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var proprietary string
		if err := rows.Scan(&proprietary); err != nil {
			return nil, err
		}
		items = append(items, proprietary)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProprietary = `-- name: GetProprietary :one
SELECT id 
FROM Proprietary
WHERE proprietary=? LIMIT 1
`

func (q *Queries) GetProprietary(ctx context.Context, proprietary string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProprietary, proprietary)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneId = `-- name: GetZoneId :one
SELECT id
FROM Zone
WHERE name=? LIMIT 1
`

func (q *Queries) GetZoneId(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getZoneId, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneType = `-- name: GetZoneType :one
SELECT id
FROM Zonetype
WHERE location_type=? LIMIT 1
`

func (q *Queries) GetZoneType(ctx context.Context, locationType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getZoneType, locationType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getZoneTypes = `-- name: GetZoneTypes :many
SELECT location_type
FROM Zonetype
`

func (q *Queries) GetZoneTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getZoneTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location_type string
		if err := rows.Scan(&location_type); err != nil {
			return nil, err
		}
		items = append(items, location_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZones = `-- name: GetZones :many
SELECT z1.name,z2.name as father,Zonetype.location_type,proprietary.proprietary
FROM Zone z1 JOIN proprietary JOIN ZoneType JOIN Zone z2 on z1.father=z2.id
`

type GetZonesRow struct {
	Name         string
	Father       string
	LocationType string
	Proprietary  string
}

func (q *Queries) GetZones(ctx context.Context) ([]GetZonesRow, error) {
	rows, err := q.db.QueryContext(ctx, getZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetZonesRow
	for rows.Next() {
		var i GetZonesRow
		if err := rows.Scan(
			&i.Name,
			&i.Father,
			&i.LocationType,
			&i.Proprietary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
