//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Connections struct {
	ID                        *int32 `sql:"primary_key"`
	FromDevicePortModelPortID int32
	FromDevicePortDeviceID    int32
	FromIPSegment             string
	ToDevicePortModelPortID   int32
	ToDevicePortDeviceID      int32
	ToIPSegment               string
	ConnectionType            int32
}
