//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type DevicePorts struct {
	ModelPortID int32 `sql:"primary_key"`
	DeviceID    int32 `sql:"primary_key"`
}
